spring.datasource.url=jdbc:postgresql://localhost:5432/tarefas_db
spring.datasource.username=tarefas_user
spring.datasource.password=tarefas123
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

jwt.secret=tarefas-api-secret-key-minimo-256-bits-abcdefghijklmnopqrstuvwxyz123456
jwt.expiration=86400000
